[versions]
kotlin = "2.3.0"

logback = "1.5.13"
postgres = "42.7.7"
mordant = "2.4.0"
ktor = "3.4.0"

[libraries]
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
postgres = { group = "org.postgresql", name = "postgresql", version.ref = "postgres" }
mordant = { group = "com.github.ajalt.mordant", name = "mordant", version.ref = "mordant" }

ktor-server-core         = { group = "io.ktor", name = "ktor-server-core-jvm" }
ktor-server-netty        = { group = "io.ktor", name = "ktor-server-netty" }
ktor-server-config-yaml  = { group = "io.ktor", name = "ktor-server-config-yaml" }
ktor-server-di           = { group = "io.ktor", name = "ktor-server-di" }
ktor-server-htmx         = { group = "io.ktor", name = "ktor-server-htmx" }
ktor-server-html-builder = { group = "io.ktor", name = "ktor-server-html-builder" }

ktor-htmx      = { group = "io.ktor", name = "ktor-htmx" }
ktor-htmx-html = { group = "io.ktor", name = "ktor-htmx-html" }

ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }